In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy

## Import gtf file

In [5]:
df_gtf = pd.read_csv("BDGP6.Ensembl.81.gtf",skiprows = 5,sep = "\t",
                     names=['seqname','source','feature','start','end','score','strand','frame','attribute'])
df_gtf

,seqname,source,feature,start,end,score,strand,frame,attribute
0,3R,FlyBase,gene,722370,722621,.,-,.,"gene_id ""FBgn0085804""; gene_version ""1""; gene_..."
1,3R,FlyBase,transcript,722370,722621,.,-,.,"gene_id ""FBgn0085804""; gene_version ""1""; trans..."
2,3R,FlyBase,exon,722370,722621,.,-,.,"gene_id ""FBgn0085804""; gene_version ""1""; trans..."
3,3R,FlyBase,gene,835381,2503907,.,+,.,"gene_id ""FBgn0267431""; gene_version ""1""; gene_..."
4,3R,FlyBase,transcript,835381,2503907,.,+,.,"gene_id ""FBgn0267431""; gene_version ""1""; trans..."
...,...,...,...,...,...,...,...,...,...
538334,211000022279342,FlyBase,transcript,1,530,.,+,.,"gene_id ""FBgn0085772""; gene_version ""1""; trans..."
538335,211000022279342,FlyBase,exon,1,530,.,+,.,"gene_id ""FBgn0085772""; gene_version ""1""; trans..."
538336,211000022279132,FlyBase,gene,1,1005,.,+,.,"gene_id ""FBgn0085825""; gene_version ""1""; gene_..."
538337,211000022279132,FlyBase,transcript,1,1005,.,+,.,"gene_id ""FBgn0085825""; gene_version ""1""; trans..."
538338,211000022279132,FlyBase,exon,1,1005,.,+,.,"gene_id ""FBgn0085825""; gene_version ""1""; trans..."

## E1 - 1: Find and report the nearest protein coding gene to the position 3R:21,378,950.

In [22]:
df_gtf.iloc[10,-1]

'gene_id "FBgn0267431"; gene_version "1"; transcript_id "FBtr0346770"; transcript_version "1"; exon_number "3"; gene_name "CG45784"; gene_source "FlyBase"; gene_biotype "protein_coding"; transcript_name "CG45784-RA"; transcript_source "FlyBase"; transcript_biotype "protein_coding"; exon_id "FBtr0346770-E3"; exon_version "1";'

In [51]:
#extract data on 3R and is gene
# 
df_3R_gene=df_gtf[(df_gtf['seqname']=='3R')&
             (df_gtf['feature']=='gene')
            ]
df_3R_gene

,seqname,source,feature,start,end,score,strand,frame,attribute
0,3R,FlyBase,gene,722370,722621,.,-,.,"gene_id ""FBgn0085804""; gene_version ""1""; gene_..."
3,3R,FlyBase,gene,835381,2503907,.,+,.,"gene_id ""FBgn0267431""; gene_version ""1""; gene_..."
47,3R,FlyBase,gene,1031171,1031354,.,+,.,"gene_id ""FBgn0039987""; gene_version ""1""; gene_..."
50,3R,FlyBase,gene,2156916,2157206,.,-,.,"gene_id ""FBgn0058182""; gene_version ""1""; gene_..."
53,3R,FlyBase,gene,2554124,3263573,.,-,.,"gene_id ""FBgn0267430""; gene_version ""1""; gene_..."
...,...,...,...,...,...,...,...,...,...
124684,3R,FlyBase,gene,32015941,32026928,.,+,.,"gene_id ""FBgn0267117""; gene_version ""1""; gene_..."
124687,3R,FlyBase,gene,32038330,32039753,.,+,.,"gene_id ""FBgn0039887""; gene_version ""1""; gene_..."
124706,3R,FlyBase,gene,32045314,32051993,.,-,.,"gene_id ""FBgn0040206""; gene_version ""1""; gene_..."
124725,3R,FlyBase,gene,32052060,32054974,.,+,.,"gene_id ""FBgn0002780""; gene_version ""1""; gene_..."
124756,3R,FlyBase,gene,32055279,32068441,.,-,.,"gene_id ""FBgn0002645""; gene_version ""1""; gene_..."

In [53]:
#extract protein coding gene
df_3R_protein_coding=df_3R_gene[ df_3R_gene['attribute'].str.contains('protein_coding')]
df_3R_protein_coding

,seqname,source,feature,start,end,score,strand,frame,attribute
3,3R,FlyBase,gene,835381,2503907,.,+,.,"gene_id ""FBgn0267431""; gene_version ""1""; gene_..."
53,3R,FlyBase,gene,2554124,3263573,.,-,.,"gene_id ""FBgn0267430""; gene_version ""1""; gene_..."
101,3R,FlyBase,gene,3322810,3354486,.,+,.,"gene_id ""FBgn0086917""; gene_version ""1""; gene_..."
110,3R,FlyBase,gene,3461351,3587054,.,-,.,"gene_id ""FBgn0010247""; gene_version ""1""; gene_..."
128,3R,FlyBase,gene,3623143,3627690,.,+,.,"gene_id ""FBgn0086378""; gene_version ""1""; gene_..."
...,...,...,...,...,...,...,...,...,...
124641,3R,FlyBase,gene,31978121,31990909,.,+,.,"gene_id ""FBgn0039886""; gene_version ""1""; gene_..."
124687,3R,FlyBase,gene,32038330,32039753,.,+,.,"gene_id ""FBgn0039887""; gene_version ""1""; gene_..."
124706,3R,FlyBase,gene,32045314,32051993,.,-,.,"gene_id ""FBgn0040206""; gene_version ""1""; gene_..."
124725,3R,FlyBase,gene,32052060,32054974,.,+,.,"gene_id ""FBgn0002780""; gene_version ""1""; gene_..."
124756,3R,FlyBase,gene,32055279,32068441,.,-,.,"gene_id ""FBgn0002645""; gene_version ""1""; gene_..."

In [73]:
df_3R_cut=copy.deepcopy(df_3R_protein_coding)
count=0
for i in range(15):
    
    while len(df_3R_cut)>1:
        count+=1
        cut_step=int(len(df_3R_cut)/2)
        if df_3R_cut.iloc[cut_step-1,3]>21378950:
            df_3R_cut=df_3R_cut[:cut_step]
        else:
            df_3R_cut=df_3R_cut[cut_step:]
print('Nearest protein coding gene to the position 3R:21,378,950 is')
      
df_3R_cut

Nearest protein coding gene to the position 3R:21,378,950 is

,seqname,source,feature,start,end,score,strand,frame,attribute
77325,3R,FlyBase,gene,21378977,21381970,.,+,.,"gene_id ""FBgn0004110""; gene_version ""1""; gene_..."

## E1 - 2: Report the gene's linear genomic distance from 3R:21,378,950.

In [74]:
distance_start = df_3R_cut['start']-21378950
distance_end = df_3R_cut['end']-21378950
print("The gene's start position is ", int(distance_start), "base from 3R:21,378,950")
print("The gene's end position is ", int(distance_end), "base from 3R:21,378,950")

The gene's start position is  27 base from 3R:21,378,950
The gene's end position is  3020 base from 3R:21,378,950

## E1 -3: How many iterations (a tally), did it take the search procedure to find the nearest gene? Report this.

In [76]:
print("It takes",count, "times to get the result.")

It takes 11 times to get the result.